FROM glassfish/server:latest

RUN wget https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-5.1.40.tar.gz \
   && tar xf mysql-connector-java-5.1.40.tar.gz \
   && cp mysql-connector-java-5.1.40/mysql-connector-java-5.1.40-bin.jar /glassfish/lib/
